eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: 8103

spring:
  application:
    name: zuul-server
  zipkin:
    base-url: http://localhost:8105
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
zuul:
  routes:
    user:
      path: /user-server/**
      serviceId: user-server
    balance:
      path: /balance-server/**
      serviceId: balance-server

