eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
server:
  port: 8103
spring:
  application:
    name: zuul-server
zuul:
  routes:
    user:
      path: /user-server/**
      serviceId: user-server
    balance:
      path: /balance-server/**
      serviceId: balance-server

