eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: ${PORT:8102}

spring:
  application:
    name: balance-server
  zipkin:
    base-url: http://localhost:8105
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8104/
#开启监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
