eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
server:
  port: 8102

spring:
  application:
    name: balance-server
  zipkin:
    base-url: http://localhost:8105
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8104/
feign.hystrix.enabled: true