spring:
  application.name: hystrix-terbine-server
server:
  port: 8889
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: user-server
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/